version: "3"
services:
  postgres:
        image: postgres
        restart: always
        environment: 
          - POSTGRES_USER=test_user
          - POSTGRES_PASSWORD=test_password
          - POSTGRES_DB=test
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
